spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boot_learn
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      dle-timeout: 30000
      maximum-pool-size: 15
      connection-init-sql: "SET NAMES utf8mb4"
server:
  port: 8080
