spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.200.59.148:3306/develop?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: '!@#456Poiuy'
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      dle-timeout: 30000
      maximum-pool-size: 15
      connection-init-sql: "SET NAMES utf8mb4"
server:
  port: 8081
logging:
  config: classpath:logback.xml
user:
  name: "马小跳"
  age: 10
  school: "向阳小学"
  subject: 语文,数学,英语
  achievement: {"language":10,"math":20,"english":30}
mybatis-plus:
  mapper-locations: classpath:com.boot.plus.mybatis.dao/*.xml
  type-aliases-package: com.boot.plus.mybatis.dao