spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.200.59.148:3306/develop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: '!@#456Poiuy'
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      dle-timeout: 30000
      maximum-pool-size: 15
      connection-init-sql: "SET NAMES utf8mb4"
  devtools:
    restart:
      additional-paths: src/main/java
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
server:
  port: 8081
#mybatis:
#  mapper-locations: com.boot.plus.mybatis.mapper.*.xml
#  type-aliases-package: com.boot.plus.mybatis.entity
#  config-locations: classpath:mybatis-generator/generatorConfig.xml
user:
  name: "马小跳"
  age: 10
  school: "向阳小学"
  subject: 语文,数学,英语
  achievement: {"language":10,"math":20,"english":30}
